New LaTeX3 implementation
kanaka/mal pull request #639
Opened 2023-07-06 14:52 UTC by asarhaddon

It requires two cosmetic changes to existing tests.

2024-08-07 18:21 UTC, kanaka requested changes
Apart from the time-ms test change (comment inline), looks really good. You'll also need to add it to `IMPLS.yml` for CI to pick it up.

2024-08-08 14:52 UTC, kanaka requested changes
Looks like it failed during image build due to the tzdata interactivity issue. This should fix it:

```
-RUN apt-get -y install texlive-latex-base
+RUN DEBIAN_FRONTEND=noninteractive apt-get -y install texlive-latex-base
```

2024-08-08 19:24 UTC, asarhaddon commented
I cannot remember exactly, but I spent at least a week in cumulated time.
I was expecting a challenge. LaTeX3 is an effort to make TeX/LaTeX as consistent as possible, despite its original design (Knuth did explicitly not want TeX to be Turing-complete).  The recommend way to implement LaTeX extensions is to use the embedded LUA interpreter.
That said, the LaTeX3 documentation is wonderful and clearly describes its purpose and limitations.
I cannot reproduce the issue locally. On my machine the `texlive-latex-base` package is at version 2024.20240706-1, while the version in the build logs is 2019-*. I will try to require ubuntu:24.04 instead of 20.04 in the Dockerfile.

2024-08-08 20:40 UTC, merged

2024-08-08 20:40 UTC, kanaka commented
Guess the latex in 20.04 was just too old.